image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test

build-and-verify:
  stage: test
  script:
    - docker build -t mi-web2 .
    - docker create --name temp mi-web2
    - docker cp temp:/mi-web ./verificacion
    - ls -l verificacion
    - docker rm temp
