image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build-image:
  stage: build
  script:
    - docker build -t miweb:latest .

deploy:
  stage: deploy
  script:
    - docker run -d --name demo-web -p 8080:80 miweb:latest
    - echo "Contenedor en ejecución para pruebas"
