image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - verify

build-image:
  stage: build
  script:
    - docker build -t mi-web:sin-nginx .
    - docker images

verify-content:
  stage: verify
  script:
    - docker create --name temp mi-web:sin-nginx
    - docker cp temp:/mi-web ./verificacion
    - ls verificacion
    - docker rm temp

